export const bestPracticesRule = {
  rules: {
    'no-var': 'error',
    'prefer-const': 'error',
    'no-shadow': 'off',
    'no-eval': 'error',
    'no-implied-eval': 'off',
    'no-new-func': 'error',
    'no-return-assign': ['error', 'always'],
    'no-return-await': 'off',
    'no-param-reassign': ['error', { props: false }],
    'no-useless-return': 'error',
    'no-else-return': ['error', { allowElseIf: false }],
    eqeqeq: ['error', 'always', { null: 'ignore' }],
    'prefer-promise-reject-errors': 'off',
    'no-iterator': 'error',
    'no-new-wrappers': 'error',
    'no-proto': 'error',
    'no-extend-native': 'error',
    'no-new-object': 'error',
    'object-shorthand': ['error', 'always', { ignoreConstructors: false, avoidQuotes: true }],
    'quote-props': ['error', 'as-needed', { keywords: false, unnecessary: true, numbers: false }],
    'dot-notation': 'off',
    'no-array-constructor': 'off',
    'array-callback-return': ['error', { allowImplicit: true, checkForEach: false }],
    'prefer-destructuring': [
      'error',
      {
        VariableDeclarator: {
          array: false,
          object: true,
        },
        AssignmentExpression: {
          array: false,
          object: false,
        },
      },
      {
        enforceForRenamedProperties: false,
      },
    ],
    'prefer-template': 'error',
    'template-curly-spacing': ['error', 'never'],
    'no-useless-concat': 'error',
    'prefer-arrow-callback': ['error', { allowNamedFunctions: false, allowUnboundThis: true }],
    'arrow-body-style': ['error', 'as-needed', { requireReturnForObjectLiteral: false }],
    'arrow-parens': ['error', 'always'],
    'no-useless-constructor': 'off',
    'no-dupe-class-members': 'off',
    'no-restricted-exports': [
      'error',
      {
        restrictedNamedExports: ['default', 'then'],
      },
    ],
    'no-restricted-imports': [
      'error',
      {
        paths: [],
        patterns: [],
      },
    ],
    'no-nested-ternary': 'warn',
    'no-unneeded-ternary': ['error', { defaultAssignment: false }],
    'no-mixed-operators': [
      'error',
      {
        groups: [
          ['%', '**'],
          ['%', '+'],
          ['%', '-'],
          ['%', '*'],
          ['%', '/'],
          ['/', '*'],
          ['&', '|', '<<', '>>', '>>>'],
          ['==', '!=', '===', '!=='],
          ['&&', '||'],
        ],
        allowSamePrecedence: false,
      },
    ],
    'nonblock-statement-body-position': ['error', 'beside', { overrides: {} }],
    'brace-style': ['error', '1tbs', { allowSingleLine: true }],
    'for-direction': 'error',
    'spaced-comment': [
      'error',
      'always',
      {
        line: {
          exceptions: ['-', '+'],
          markers: ['=', '!', '/'],
        },
        block: {
          exceptions: ['-', '+'],
          markers: ['=', '!', ':', '::'],
          balanced: true,
        },
      },
    ],
    'no-trailing-spaces': [
      'error',
      {
        skipBlankLines: false,
        ignoreComments: false,
      },
    ],
    'comma-style': [
      'error',
      'last',
      {
        exceptions: {
          ArrayExpression: false,
          ArrayPattern: false,
          ArrowFunctionExpression: false,
          CallExpression: false,
          FunctionDeclaration: false,
          FunctionExpression: false,
          ImportDeclaration: false,
          ObjectExpression: false,
          ObjectPattern: false,
          VariableDeclaration: false,
          NewExpression: false,
        },
      },
    ],
    'comma-dangle': [
      'error',
      {
        arrays: 'always-multiline',
        objects: 'always-multiline',
        imports: 'always-multiline',
        exports: 'always-multiline',
        functions: 'always-multiline',
      },
    ],
    radix: 'error',
    'no-new': 'error',
  },
};
